### ISSUE TITLE
(dev) To Do List for next WLED-MM release 14.7

### ISSUE THREAD

**Issue by softhack007** [MoonModules/WLED#175]
Let's collect open ends that should be solved before we make the next MoonModules release.
From my view, these topics are currently important:

#### HUB75 "roundup":
  * [x] Integrate pinout for T7-S3 and related "MoonHUB" board
  * [x] User setting for "clock phase" (and if possible: dropdown for shiftReg driver) @netmindz 
  * [ ] merge & test #169 @netmindz 
  * [ ] merge & test #185 @netmindz 

#### Generic bugs:
  * [x] FastPATH: solve problems with single-column/single-row effects on a 2D panel (currently not working / crashing) @softhack007 
  * [x] test and merge #176 @softhack007 
  * [ ] FastPATH: find a workaround for "custom bus start indices" (currently only the first matching bus gets all pixels, others stay blank) @softhack007 

#### Art-Net driver:
  * [x] #179 merge improved driver from @troyhacks

#### WLED "Dual Booting":
  * [X] #157 Press "^" on the serial console to reboot to other OTA partition, if valid and exists. @troyhacks 

#### Effects/1D Expands:
  * [ ] #197 @softhack007 
  * [X] #143 @troyhacks 
  * [X] #147 @brandon502 
  * [X] #171 @brandon502
  * [x] #181 @brandon502
  * [x] cfce1c3062ed557610cfa9e735cd3582312548e3 Drift speed optimization @softhack007
  * [X] #199 by @softhack007
  * [X] DNA new slider "phases" (by @ewoudwijma and @softhack007)
  * [X] 402786c14e15799b2d4910f8298c69ab5395cbd0 GEQ "Flat Mode" for 1D strips @softhack007

#### Audio Hardware:
  * [X] #144 @troyhacks 
  
#### Optional (if time allows):
  * [ ] merge #152 @softhack007 

<br/>

## After Party (inform users about future)
  * drop active support for 8266
  * move to arduino-esp32 v2.0.14 (all builds including classic esp32)
  * audioreactive: user-configurable low-cut filter frequency
  * we might keep a few basic configs that are still OTA-compatible with upstream
  * if possible: enable LTO (link time optimization) to save flash on 4MB builds --> https://github.com/Aircoookie/WLED/pull/4167
    * plan B: move to "512kB LittleFS" partition for all 4MB boards --> installer sites need updates, no OTA from Aircoookie WLED
  * ESP32-C6 and ESP32-P4 support merged in (may be limited in output types for now)

### Technical
  * move to ESP-DSP for FFT routines
  * remove old non-fastPath code (so every build is fastPath)
  * use heap_caps_[mc]alloc_prefer() instead of [mc]alloc() - automatically uses PSRAM in case that normal RAM is not available
  * ... or the reverse, always prefer PSRAM if we can accept the potential speed decreases, depending on hardware.
  * Investigate hard-limits for memory so everything we need is allocated at boot, and we try to live within constraints
  * Integrate Pinwheel2 https://github.com/Aircoookie/WLED/pull/4185
  * Image support: panel backdrops (jpg), animated pixelart (gif, maybe png)
  * Possible H264 video (ESP32-P4, long way off right now, no useful code in IDF v5.3.1 yet)

**Comment by softhack007** [comment]
all done.
